name: flutter_custom_widgets
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  iconsax: ^0.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
