name: flutter_custom_widgets
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_gen: ^5.9.0
  font_awesome_flutter: ^10.8.0
  iconsax: ^0.0.8
  screenshot: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/icons/
    # - assets/sounds/
